# Auto-generated by preprocess_walk_log_v2.py
# Run this from the train repository root or adjust $TrainRoot below.
$TrainRoot = "C:\Users\sinsu\Desktop\soccer_ws\train"
Set-Location $TrainRoot

python scripts/csv_to_npz.py --headless --input_file "c:\Users\sinsu\Desktop\soccer_ws\train\_tmp_cmd_test\csv\a.csv" --input_fps 50 --output_name "c:\Users\sinsu\Desktop\soccer_ws\train\_tmp_cmd_test\npz\a.npz" --output_fps 50
