#!/usr/bin/env bash
# Auto-generated by preprocess_walk_log_v2.py (Path fixed for Linux environment)
set -euo pipefail
TRAIN_ROOT="/home/user/booster_train"
cd "$TRAIN_ROOT"

python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0001_vxp0.20_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0001_vxp0.20_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0002_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0002_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0003_vxm0.20_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0003_vxm0.20_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0004_vxm0.50_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0004_vxm0.50_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0005_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0005_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0006_vxp0.50_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0006_vxp0.50_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0007_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0007_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0008_vxm1.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0008_vxm1.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0009_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0009_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0010_vxp1.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0010_vxp1.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0011_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0011_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0012_vxm1.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0012_vxm1.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0013_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0013_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0014_vxp0.00_vyp0.20_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0014_vxp0.00_vyp0.20_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0015_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0015_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0016_vxp0.00_vym0.20_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0016_vxp0.00_vym0.20_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0017_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0017_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0018_vxp0.00_vyp0.50_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0018_vxp0.00_vyp0.50_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0019_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0019_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0020_vxp0.00_vym0.50_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0020_vxp0.00_vym0.50_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0021_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0021_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0022_vxp0.00_vyp1.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0022_vxp0.00_vyp1.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0023_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0023_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0024_vxp0.00_vym1.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0024_vxp0.00_vym1.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0025_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0025_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0026_vxp0.00_vyp0.00_vyawp0.50.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0026_vxp0.00_vyp0.00_vyawp0.50.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0027_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0027_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0028_vxp0.00_vyp0.00_vyawm0.50.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0028_vxp0.00_vyp0.00_vyawm0.50.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0029_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0029_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0030_vxp0.00_vyp0.00_vyawp1.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0030_vxp0.00_vyp0.00_vyawp1.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0031_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0031_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0032_vxp0.00_vyp0.00_vyawm1.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0032_vxp0.00_vyp0.00_vyawm1.00.npz" --output_fps 50
python scripts/csv_to_npz.py --headless --input_file "processed_walks_002/csv/clip_0033_vxp0.00_vyp0.00_vyawp0.00.csv" --input_fps 50 --output_name "processed_walks_002/npz/clip_0033_vxp0.00_vyp0.00_vyawp0.00.npz" --output_fps 50
